
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'PROGRAMDO DUMBO_BLOCK ENDFOR EXPRESSION EXPRESSION_LIST FOR IN PRINT STRING STRING_EXPRESSION STRING_LIST STRING_LIST_INTERIOR TXT VARIABLE\n    PROGRAM : TXT\n            | DUMBO_BLOCK\n    \n    PROGRAM : TXT PROGRAM\n            | DUMBO_BLOCK PROGRAM\n            | STRING\n    '
    
_lr_action_items = {'TXT':([0,2,3,],[2,2,2,]),'DUMBO_BLOCK':([0,2,3,],[3,3,3,]),'STRING':([0,2,3,],[4,4,4,]),'$end':([1,2,3,4,5,6,],[0,-1,-2,-5,-3,-4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'PROGRAM':([0,2,3,],[1,5,6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> PROGRAM","S'",1,None,None,None),
  ('PROGRAM -> TXT','PROGRAM',1,'p_program_single','dumbo.py',67),
  ('PROGRAM -> DUMBO_BLOCK','PROGRAM',1,'p_program_single','dumbo.py',68),
  ('PROGRAM -> TXT PROGRAM','PROGRAM',2,'p_program_double','dumbo.py',76),
  ('PROGRAM -> DUMBO_BLOCK PROGRAM','PROGRAM',2,'p_program_double','dumbo.py',77),
  ('PROGRAM -> STRING','PROGRAM',1,'p_program_double','dumbo.py',78),
]
